#region Auto-Generated Class Description
/*
 * This class was auto generated by the IngresDaoLibraryGenerator.py script.
 * 
 * It will configure all of the auto-generated web service urls for both local
 * and deployed versions. It assumes the local versions web services will be hosted
 * at the port number defined by LocalhostWebservicePort in the STATIC PROPERTIES region.
 */
#endregion

using System.Configuration;
using System;

namespace _WcfMyBatisUtilLibrary
{
    public class Configurations
    {
        #region Properties (do not edit/change)
        public static string ServiceRoot = "";
        private static string ServiceLibraryName = "";
        #endregion

        #region Constructor
        private static void ConfigureBase()
        {
            ServiceRoot = ConfigurationManager.AppSettings["_WcfMyBatisServiceLibrary.ServiceRoot"];
            if (ServiceRoot == null || ServiceRoot.Equals(""))
            {
                ServiceRoot = "http://localhost:9128";
            }

            ServiceLibraryName = ConfigurationManager.AppSettings["_WcfMyBatisServiceLibrary.ServiceLibraryName"];
            if (ServiceRoot == null || ServiceRoot.Equals(""))
            {
                ServiceRoot = "_WcfMyBatisServiceLibrary";
            }
        }

        public static string GetServiceUrl(Type type)
        {
            return ServiceRoot + "/" + ServiceLibraryName + "." + type.Name.ToString() +".svc";
        }

        static Configurations()
        {
            ConfigureBase();
        }
        #endregion
    }
}