//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.0
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db_TeXML.Wpf {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Db_TeXML.Wpf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Db_TeXML {
            get {
                object obj = ResourceManager.GetObject("Db_TeXML", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   #########################################################################
        ///# Db TeXML - Database Translation Engine Mark-up Language Specifications:
        ///#########################################################################
        ///
        ///#########################################################################
        ///1. Database Connections
        ///
        ///To ensure connectivity to your postgresql database, please remember to allow access from local addresses and your local intra-net.
        ///
        ///To do this please add the following lines to your [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbTeXML_Language_Specifications {
            get {
                return ResourceManager.GetString("DbTeXML_Language_Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon dbtexml_new2 {
            get {
                object obj = ResourceManager.GetObject("dbtexml_new2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   table_name	column_name	data_type	data_type_short	character_maximum_length	column_default	column_nullable	is_primary_key
        ///alltypes	type01	bigint	int8	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​
        ///alltypes	type02	bigint	int8	​(NULL)​	nextval(&apos;alltypes_type02_seq&apos;::regclass)	not nullable	​(NULL)​
        ///alltypes	type03	bit	bit	1	​(NULL)​	​(NULL)​	​(NULL)​
        ///alltypes	type04	bit varying	varbit	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​
        ///alltypes	type05	boolean	bool	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​
        ///alltypes	type06	box	box	​(NULL)​	 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string practice_select_information_schema_columns {
            get {
                return ResourceManager.GetString("practice_select_information_schema_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   table_catalog	table_schema	table_name	table_type	self_referencing_column_name	reference_generation	user_defined_type_catalog	user_defined_type_schema	user_defined_type_name	is_insertable_into	is_typed	commit_action
        ///practice	public	alltypes	BASE TABLE	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​	YES	NO	​(NULL)​
        ///practice	public	classes	BASE TABLE	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​	YES	NO	​(NULL)​
        ///practice	public	schedule	BASE TABLE	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​	​(NULL)​	YES	NO	​(NULL)​
        ///pra [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string practice_select_information_schema_tables {
            get {
                return ResourceManager.GetString("practice_select_information_schema_tables", resourceCulture);
            }
        }
    }
}
